# Generated by Django 6.1.1 on 2026-09-29 11:42

import uuid

from django.db import migrations

def gen_unique_tokens(apps, schema_editor):
    Workspace = apps.get_model('workspaces', 'Workspace')
    for workspace in Workspace.objects.all():
        workspace.invite_token = uuid.uuid4()
        workspace.save(update_fields=['invite_token'])

class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0002_workspace_invite_token_workspace_members_and_more"),
    ]

    operations = [
        migrations.RunPython(gen_unique_tokens, reverse_code=migrations.RunPython.noop),
    ]
