# Generated by Django 6.1.1 on 2026-09-29 11:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0003_populate_invite_tokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="invite_token",
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
    ]
