# Generated by Django 6.1.1 on 2026-10-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="title",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="survey",
            name="logic_rules",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="survey",
            name="settings",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="survey",
            name="title",
            field=models.CharField(max_length=256),
        ),
    ]
