# Generated by Django 6.1.1 on 2026-10-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0002_alter_question_title_alter_survey_logic_rules_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="properties",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
